## Die verbindliche Farbpalette von Stillwater. Handgemalte Sprites müssen
## sich daran halten, sonst fällt der Stil auseinander.
class_name Palette
extends RefCounted

const COLORS := {
	&"sky_high":    Color("2f4858"),
	&"sky_low":     Color("6a8ba0"),
	&"water_deep":  Color("1f3b47"),
	&"water_mid":   Color("2e5f6b"),
	&"water_light": Color("478a8f"),
	&"foam":        Color("bcd9d2"),
	&"reed_dark":   Color("2f4a34"),
	&"reed":        Color("4d7a4a"),
	&"reed_light":  Color("7ba85f"),
	# Sunset Coast: waermere Daemmerung ueber offenem Wasser.
	&"dusk_high":   Color("3d3350"),
	&"dusk_low":    Color("e08a5c"),
	&"sea_deep":    Color("21374f"),
	&"sea_light":   Color("4a7f9e"),
	&"sea_foam":    Color("f2d6bd"),
	&"sand_dark":   Color("6b4f3a"),
	&"sand":        Color("b08a63"),
	&"sand_light":  Color("d6b489"),
	# Nebelmoor bei Nacht: kalt, gedaempft, ein einziger warmer Fleck (Irrlicht).
	&"night_high":  Color("141a2b"),
	&"night_low":   Color("2d3550"),
	&"bog_deep":    Color("101a1c"),
	&"bog_light":   Color("223d3a"),
	&"mist":        Color("8ea8a5"),
	&"peat_dark":   Color("1c1a16"),
	&"peat":        Color("332d24"),
	&"willow":      Color("46543f"),
	&"wisp":        Color("cfe07a"),
	# Besucher am Steg: der Waschbär und der Rabe.
	&"fur":         Color("8a8d92"),
	&"fur_dark":    Color("4e5257"),
	&"fur_light":   Color("c3c7cc"),
	&"raven":       Color("232630"),
	&"raven_sheen": Color("4a5570"),
	&"beak":        Color("d9cdb4"),
	# Frostbucht: Eis, Polarlicht, offenes kaltes Wasser.
	&"polar_high":  Color("15243d"),
	&"polar_low":   Color("3c6a8e"),
	&"aurora":      Color("6ff2b8"),
	&"ice_deep":    Color("13435c"),
	&"ice_light":   Color("6fb6cf"),
	&"ice_foam":    Color("e8f6ff"),
	&"snow":        Color("dbe9f2"),
	&"snow_dark":   Color("9db4c4"),
	# Tiefe Zisterne: Fackelschein auf altem Stein, kein Himmel.
	&"vault_high":  Color("120f10"),
	&"vault_low":   Color("2b211c"),
	&"torch":       Color("ffb35c"),
	&"cistern_deep": Color("101c1e"),
	&"cistern_light": Color("2f5654"),
	&"cistern_foam": Color("b8d6c8"),
	&"stone":       Color("4a4038"),
	&"stone_light": Color("6d6055"),
	# Wolkensee: ueber den Wolken, sehr hell, sehr weit.
	&"sky_pale":    Color("cfe6ff"),
	&"sky_mid":     Color("7fb0e8"),
	&"cloud":       Color("f4f8ff"),
	&"cloud_dark":  Color("c3d4e8"),
	&"high_deep":   Color("3d74c4"),
	&"high_light":  Color("8fc3f0"),
	# Sternensee: Wasser ohne Ufer, Licht von unten.
	&"void_high":   Color("07060f"),
	&"void_low":    Color("1b1436"),
	&"star":        Color("fdf6d8"),
	&"nebula":      Color("7a4fd0"),
	&"void_deep":   Color("0d0a1c"),
	&"void_light":  Color("3a2d6b"),
	&"void_foam":   Color("b9a6f0"),
	&"wood_dark":   Color("4a3626"),
	&"wood":        Color("7a5a3c"),
	&"wood_light":  Color("a5825a"),
	&"skin_0":      Color("f6ddc4"),
	&"skin_1":      Color("e8be9a"),
	&"skin_2":      Color("c68c63"),
	&"skin_3":      Color("8d5a3c"),
	&"skin_4":      Color("5c3826"),
	# Keine Hauttoene mehr, sondern Fantasie: sie kosten, die echten nicht.
	&"skin_moss":   Color("6f9455"),
	&"skin_ice":    Color("9fc7d6"),
	&"skin_ash":    Color("8f8a9c"),
	&"cloth_red":   Color("b4523f"),
	&"cloth_blue":  Color("3f6fb4"),
	&"cloth_green": Color("4a9455"),
	&"cloth_grey":  Color("6f7a75"),
	&"cloth_ochre": Color("c8913f"),
	&"cloth_plum":  Color("6b4470"),
	&"oilskin":     Color("8f6a2c"),
	&"leather":     Color("6b4326"),
	&"denim":       Color("39537f"),
	&"bone":        Color("d9cfae"),
	&"hair_dark":   Color("2c2320"),
	&"hair_warm":   Color("8a5a2c"),
	&"hair_pale":   Color("d8c48a"),
	&"hair_moss":   Color("4f7a53"),
	&"hair_snow":   Color("e6e9ea"),
	&"hair_teal":   Color("3aa89b"),
	&"hair_violet": Color("8a5fd0"),
	&"hair_pink":   Color("e07aa8"),
	&"silver":      Color("b9c3c8"),
	&"accent":      Color("f0c05a"),
	&"outline":     Color("1a2320"),
	&"shadow":      Color("141c1a"),
}

static func get_color(name: StringName) -> Color:
	return COLORS.get(name, Color.MAGENTA)
